from config.env import get_env, get_int_env


CHANNEL_ANALYSIS_REMOTE_URL = get_env("EKKO_ANALYSIS_REMOTE_URL", default="")
CHANNEL_ANALYSIS_REMOTE_TOKEN = get_env("EKKO_ANALYSIS_REMOTE_TOKEN", default="")
CHANNEL_ANALYSIS_REMOTE_TIMEOUT_SECONDS = get_int_env(
    "EKKO_ANALYSIS_REMOTE_TIMEOUT_SECONDS",
    default=120,
)
CHANNEL_ANALYSIS_MAX_MESSAGES = get_int_env("EKKO_ANALYSIS_MAX_MESSAGES", default=80)
CHANNEL_ANALYSIS_MAX_CHARS = get_int_env("EKKO_ANALYSIS_MAX_CHARS", default=20000)
