from config.env import get_float_env, get_int_env


VOICE_MESSAGE_EXCITEMENT_AMPLITUDE_WEIGHT = get_float_env(
    "EKKO_VOICE_EXCITEMENT_AMPLITUDE_WEIGHT",
    default=0.5,
)
VOICE_MESSAGE_EXCITEMENT_CHAR_RATE_WEIGHT = get_float_env(
    "EKKO_VOICE_EXCITEMENT_CHAR_RATE_WEIGHT",
    default=0.3,
)
VOICE_MESSAGE_EXCITEMENT_PEAK_RATE_WEIGHT = get_float_env(
    "EKKO_VOICE_EXCITEMENT_PEAK_RATE_WEIGHT",
    default=0.2,
)
VOICE_MESSAGE_EXCITEMENT_BASELINE_SENTENCES = get_int_env(
    "EKKO_VOICE_EXCITEMENT_BASELINE_SENTENCES",
    default=10,
)
VOICE_MESSAGE_EXCITEMENT_FULL_SCORE_RATIO = get_float_env(
    "EKKO_VOICE_EXCITEMENT_FULL_SCORE_RATIO",
    default=1.8,
)
VOICE_MESSAGE_EXCITEMENT_THRESHOLD = get_float_env(
    "EKKO_VOICE_EXCITEMENT_THRESHOLD",
    default=0.68,
)
VOICE_MESSAGE_EXCITEMENT_MIN_COMPOSITE_METRICS = get_int_env(
    "EKKO_VOICE_EXCITEMENT_MIN_COMPOSITE_METRICS",
    default=2,
)
