from config.env import get_int_env


STREAM_VAD_SAMPLE_RATE = get_int_env("EKKO_STREAM_VAD_SAMPLE_RATE", default=16000)
STREAM_VAD_FRAME_MS = get_int_env("EKKO_STREAM_VAD_FRAME_MS", default=20)
STREAM_VAD_MODE = get_int_env("EKKO_STREAM_VAD_MODE", default=1)
STREAM_VAD_START_FRAMES = get_int_env("EKKO_STREAM_VAD_START_FRAMES", default=2)
STREAM_VAD_PRE_SPEECH_MS = get_int_env("EKKO_STREAM_VAD_PRE_SPEECH_MS", default=200)
STREAM_VAD_MIN_SPEECH_MS = get_int_env("EKKO_STREAM_VAD_MIN_SPEECH_MS", default=220)
STREAM_VAD_INACTIVITY_MS = get_int_env("EKKO_STREAM_VAD_INACTIVITY_MS", default=650)
