from config.env import get_env, get_int_env


VOICE_MESSAGE_ASR_LANGUAGE = get_env("EKKO_ASR_LANGUAGE", default="zh")
VOICE_MESSAGE_ASR_REMOTE_QUEUE_URL = get_env("EKKO_ASR_REMOTE_QUEUE_URL", default="")
VOICE_MESSAGE_ASR_REMOTE_TOKEN = get_env("EKKO_ASR_REMOTE_TOKEN", default="")
VOICE_MESSAGE_ASR_REMOTE_TIMEOUT_SECONDS = get_int_env("EKKO_ASR_REMOTE_TIMEOUT_SECONDS", default=30)
VOICE_MESSAGE_ASR_CALLBACK_URL = get_env("EKKO_ASR_CALLBACK_URL", default="")
VOICE_MESSAGE_ASR_CALLBACK_TOKEN = get_env("EKKO_ASR_CALLBACK_TOKEN", default="")
VOICE_MESSAGE_ASR_RESTORE_INTERVAL_SECONDS = get_int_env("EKKO_ASR_RESTORE_INTERVAL_SECONDS", default=30)
