from __future__ import annotations


TRANSCRIPTION_PENDING = "pending"
TRANSCRIPTION_PROCESSING = "processing"
TRANSCRIPTION_DONE = "done"
TRANSCRIPTION_FAILED = "failed"
TRANSCRIPTION_DROPPED = "dropped"

ACTIVE_TRANSCRIPTION_STATUSES = [
    TRANSCRIPTION_PENDING,
    TRANSCRIPTION_PROCESSING,
]
